# Generated by Django 3.1.14 on 2023-08-05 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau')], default='herr', max_length=10)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='Schreiben Sie hier unten Ihre Nachricht')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_salutation', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau')], default='herr', max_length=10)),
                ('reviewer_firstname', models.CharField(max_length=50)),
                ('reviewer_lastname', models.CharField(max_length=50)),
                ('reviewer_email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('reviewer_phone_number', models.CharField(blank=True, max_length=50)),
                ('reviewer_projectType', models.CharField(choices=[('neubau', 'Neubau'), ('renovierung', 'Renovierung'), ('umbau', 'Umbau'), ('industrieprojekt', 'Industrieprojekt'), ('andere', 'andere')], default='neubau', max_length=50)),
                ('reviewer_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=10)),
                ('reviewer_content', models.TextField(verbose_name='Schreiben Sie hier unten Ihre Nachricht')),
                ('reviewer_confirmation', models.CharField(choices=[('ja', 'Ja'), ('nein', 'Nein')], default='ja', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
