# Generated by Django 3.1.14 on 2023-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='salutation',
            field=models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau')], max_length=50),
        ),
    ]
