# Generated by Django 3.1.14 on 2023-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='reviewer_confirmation',
            field=models.CharField(choices=[('ja', 'Ja'), ('nein', 'Nein')], default='ja', max_length=10, verbose_name='Dürfen wir Ihre Bewertung auf unserer Website oder Marketingmaterialien veröffentlichen?'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='reviewer_projectType',
            field=models.CharField(choices=[('neubau', 'Neubau'), ('renovierung', 'Renovierung'), ('umbau', 'Umbau'), ('industrieprojekt', 'Industrieprojekt'), ('andere', 'andere')], default='neubau', max_length=50, verbose_name='Art des Projekts'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='reviewer_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=10, verbose_name='Gesamtbewertung'),
        ),
    ]
