# Generated by Django 3.1.14 on 2023-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_customerreview_reviewer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='reviewer_rating',
            field=models.CharField(choices=[('1', '1 (Sehr unzufrieden)'), ('2', '2 (Unzufrieden)'), ('3', '3 (Neutral)'), ('4', '4 (Zufrieden)'), ('5', '5 (Sehr zufrieden)')], default='5', max_length=10, verbose_name='Gesamtbewertung'),
        ),
    ]
