# Generated by Django 3.1.14 on 2023-08-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20230802_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='salutation',
            field=models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau')], default='herr', max_length=10),
        ),
    ]
