# Generated by Django 3.1.14 on 2023-08-02 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20230802_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.TextField(verbose_name='Schreiben Sie hier unten Ihre Nachricht'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=80, validators=[django.core.validators.EmailValidator(message='Invalid Email')]),
        ),
    ]
